import React from 'react';
import './calendar.scss';

function CalendarBackground() {
  return (
    <div className="calendar-wrap">
      <div className="dayname-row">
        <div className="dayname-left"></div>
        <div className="dayname-wrap">
          <div className="dayname">MON</div>
          <div className="dayname">TUE</div>
          <div className="dayname">WED</div>
          <div className="dayname">THUR</div>
          <div className="dayname">FRI</div>
          <div className="dayname">SAT</div>
        </div>
      </div>
      <div className="full-cal">
        <div className="full-cal-times">
          <div className="cal-time">6:00 am</div>
          <div className="cal-time">6:15 am</div>
          <div className="cal-time">6:30 am</div>
          <div className="cal-time">6:45 am</div>
          <div className="cal-time">7:00 am</div>
          <div className="cal-time">7:15 am</div>
          <div className="cal-time">7:30 am</div>
          <div className="cal-time">7:45 am</div>
          <div className="cal-time">8:00 am</div>
          <div className="cal-time">8:15 am</div>
          <div className="cal-time">8:30 am</div>
          <div className="cal-time">8:45 am</div>
          <div className="cal-time">9:00 am</div>
          <div className="cal-time">9:15 am</div>
          <div className="cal-time">9:30 am</div>
          <div className="cal-time">9:45 am</div>
          <div className="cal-time">10:00 am</div>
          <div className="cal-time">10:15 am</div>
          <div className="cal-time">10:30 am</div>
          <div className="cal-time">11:00 am</div>
          <div className="cal-time">11:15 am</div>
          <div className="cal-time">11:30 am</div>
          <div className="cal-time">11:45 am</div>
          <div className="cal-time">12:00 pm</div>
          <div className="cal-time">12:15 pm</div>
          <div className="cal-time">12:30 pm</div>
          <div className="cal-time">12:45 pm</div>
          <div className="cal-time">1:00 pm</div>
          <div className="cal-time">1:15 pm</div>
          <div className="cal-time">1:30 pm</div>
          <div className="cal-time">1:45 pm</div>
          <div className="cal-time">2:00 pm</div>
          <div className="cal-time">2:15 pm</div>
          <div className="cal-time">2:30 pm</div>
          <div className="cal-time">2:45 pm</div>
          <div className="cal-time">3:00 pm</div>
          <div className="cal-time">3:15 pm</div>
          <div className="cal-time">3:30 pm</div>
          <div className="cal-time">3:45 pm</div>
          <div className="cal-time">4:00 pm</div>
          <div className="cal-time">4:15 pm</div>
          <div className="cal-time">4:30 pm</div>
          <div className="cal-time">4:45 pm</div>
          <div className="cal-time">5:00 pm</div>
          <div className="cal-time">5:15 pm</div>
          <div className="cal-time">5:30 pm</div>
          <div className="cal-time">5:45 pm</div>
          <div className="cal-time">6:00 pm</div>
          <div className="cal-time">6:15 pm</div>
          <div className="cal-time">6:30 pm</div>
          <div className="cal-time">6:45 pm</div>
          <div className="cal-time">7:00 pm</div>
          <div className="cal-time">7:15 pm</div>
          <div className="cal-time">7:30 pm</div>
          <div className="cal-time">7:45 pm</div>
          <div className="cal-time">8:00 pm</div>
          <div className="cal-time">8:15 pm</div>
          <div className="cal-time">8:30 pm</div>
          <div className="cal-time">8:45 pm</div>
          <div className="cal-time">9:00 pm</div>
          <div className="cal-time">9:15 pm</div>
          <div className="cal-time">9:30 pm</div>
          <div className="cal-time">9:45 pm</div>
          <div className="cal-time">10:00 pm</div>
        </div>
        <div className="full-cal-body">
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
          <div className="full-cal-date-time-box"></div>
        </div>
      </div>
    </div>
  );
}

export default CalendarBackground;
